[package]
name = "wasm-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # WebAssembly Compile

[dependencies]
wasm-bindgen = "0.2"    # Intreactive to JavaScript
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"